### ISSUE TITLE
Resolve connection timeout error

### ISSUE THREAD

**Issue by cbabnik** [cbabnik/discord_bot#36]
This happens sometimes days apart, so next time it happens print out the error log here

**Comment by cbabnik** [comment]
```
events.js:173
    throw err; // Unhandled 'error' event
    ^

Error [ERR_UNHANDLED_ERROR]: Unhandled error. ([object Object])
    at Client.emit (events.js:171:17)
    at WebSocketConnection.onError (Y:\Projects\BuckBot\node_modules\discord.js\src\client\websocket\WebSocketConnection.js:374:17)
    at WebSocket.onError (Y:\Projects\BuckBot\node_modules\ws\lib\event-target.js:128:16)
    at WebSocket.emit (events.js:182:13)
    at ClientRequest.req.on (Y:\Projects\BuckBot\node_modules\ws\lib\websocket.js:568:15)
    at ClientRequest.emit (events.js:182:13)
    at TLSSocket.socketErrorListener (_http_client.js:391:9)
    at TLSSocket.emit (events.js:182:13)
    at emitErrorNT (internal/streams/destroy.js:82:8)
    at emitErrorAndCloseNT (internal/streams/destroy.js:50:3)
```

**Comment by cbabnik** [comment]
These will typically happen from missing a .catch , if the problem still exists go on a hunt for unhandled promises.
